
@startuml

top to bottom direction

map p0_0 {
  x => 12
  y => 34
}

map p0_1 {
  x => 43
  y => 65
}

map p1_0 {
  x => 43
  y => 78
}

map p1_1 {
  x => 23
  y => 34
}

map p2_0 {
  x => 54
  y => 65
}

map p2_1 {
  x => 67
  y => 98
}


map line0 {
 from *--> p0_0
 to *--> p0_1
}

map line1 {
 from *--> p1_0
 to *--> p1_1
}

map line2 {
 from *--> p2_0
 to *--> p2_1
}

map "new Lines[]" as Lines {
 0 *--> line0
 1 *--> line1
 2 *--> line2
}

@enduml

